# Generated by Django 3.2 on 2021-05-01 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60)),
                ('director', models.CharField(max_length=60)),
                ('genre', models.CharField(max_length=60)),
                ('rating', models.IntegerField()),
                ('release_date', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='Movies',
        ),
    ]
